[build]
builder = "nixpacks"
buildCommand = "./gradlew clean build -x test"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar build/libs/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
